    ARDUINO_DIR   = /usr/share/arduino
    ARDMK_DIR     = /usr/share/arduino
    ARDMK_PATH    = /usr/bin
    AVR_TOOLS_DIR = /usr


ISP_PORT = /dev/ttyUSB*
BOARD_TAG    = Duemilanove
MONITOR_PORT = /dev/ttyUSB*
include /home/noah/Classes/ECE110/Arduino-Makefile/arduino-mk/Arduino.mk
